package com.doFast.dofastapp.wallet.enums;

public enum WalletTransactionType {
    TOP_UP,
    JOB_PUBLICATION_FUNDING,
    ESCROW_LOCK,
    ESCROW_ADJUSTMENT_LOCK,
    ESCROW_ADJUSTMENT_REFUND,
    ESCROW_RELEASE,
    EXPENSE_BUDGET_LOCK,
    EXPENSE_REIMBURSEMENT,
    EXPENSE_BUDGET_REFUND,
    JOB_PUBLICATION_RESERVE,
    JOB_PUBLICATION_RELEASE,
    PAYOUT_RESERVE,
    PAYOUT_RESTORE,
    CHARGEBACK_RECOVERY,
    CHARGEBACK_REINSTATEMENT,
    WITHDRAW,
    REFUND
}
