package com.doFast.dofastapp.notification.enums;

public enum NotificationType {
    JOB_ACCEPTED,
    COMPLETION_REQUESTED,
    JOB_COMPLETED,
    JOB_CANCELLATION_REQUESTED,
    JOB_CANCELLATION_DECLINED,
    JOB_CANCELLATION_WITHDRAWN,
    JOB_CANCELLED,
    DISPUTE_OPENED,
    DISPUTE_CLAIMED,
    DISPUTE_RESOLVED,
    CHAT_MESSAGE,
    REVIEW_RECEIVED,
    VERIFICATION_APPROVED,
    VERIFICATION_REJECTED,
    VERIFICATION_REVOKED
}
