package com.doFast.dofastapp.notification.enums;

public enum NotificationType {
    JOB_ACCEPTED,
    JOB_PROPOSAL_RECEIVED,
    JOB_PROPOSAL_ACCEPTED,
    COMPLETION_REQUESTED,
    JOB_COMPLETED,
    JOB_CANCELLATION_REQUESTED,
    JOB_CANCELLATION_DECLINED,
    JOB_CANCELLATION_WITHDRAWN,
    JOB_CANCELLED,
    DISPUTE_OPENED,
    DISPUTE_CLAIMED,
    DISPUTE_RESOLVED,
    CHAT_MESSAGE,
    REVIEW_RECEIVED,
    SAVED_SEARCH_MATCH,
    JOB_REPORT_REVIEWED,
    JOB_REPORT_DISMISSED,
    VERIFICATION_APPROVED,
    VERIFICATION_REJECTED,
    VERIFICATION_REVOKED
}
