spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/dofast}
    username: ${SPRING_DATASOURCE_USERNAME:dofast}
    password: ${SPRING_DATASOURCE_PASSWORD:dofast-local-password}
  jpa:
    show-sql: false

logging:
  level:
    com.doFast.dofastapp: DEBUG
