CREATE TABLE identity_verifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    version INTEGER NOT NULL DEFAULT 0,
    user_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    provider VARCHAR(32) NOT NULL,
    provider_reference VARCHAR(255) NULL,
    requested_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    reviewed_at TIMESTAMP(6) WITHOUT TIME ZONE NULL,
    verified_at TIMESTAMP(6) WITHOUT TIME ZONE NULL,
    revoked_at TIMESTAMP(6) WITHOUT TIME ZONE NULL,
    reviewed_by_id BIGINT NULL,
    decision_reason VARCHAR(500) NULL,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_identity_verifications PRIMARY KEY (id),
    CONSTRAINT uk_identity_verifications_user UNIQUE (user_id),
    CONSTRAINT fk_identity_verifications_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_identity_verifications_reviewed_by FOREIGN KEY (reviewed_by_id) REFERENCES users (id),
    CONSTRAINT chk_identity_verifications_status CHECK (
        status IN ('PENDING', 'VERIFIED', 'REJECTED', 'REVOKED')
    ),
    CONSTRAINT chk_identity_verifications_provider CHECK (length(btrim(provider)) > 0),
    CONSTRAINT chk_identity_verifications_reason CHECK (
        decision_reason IS NULL OR length(decision_reason) <= 500
    )
);

CREATE INDEX idx_identity_verifications_status_requested
    ON identity_verifications (status, requested_at DESC, id DESC);
CREATE INDEX idx_identity_verifications_reviewed_by
    ON identity_verifications (reviewed_by_id);
CREATE UNIQUE INDEX uk_identity_verifications_provider_reference
    ON identity_verifications (provider, provider_reference)
    WHERE provider_reference IS NOT NULL;

CREATE TABLE identity_verification_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    verification_id BIGINT NOT NULL,
    actor_user_id BIGINT NOT NULL,
    event_type VARCHAR(24) NOT NULL,
    from_status VARCHAR(20) NULL,
    to_status VARCHAR(20) NOT NULL,
    reason VARCHAR(500) NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_identity_verification_events PRIMARY KEY (id),
    CONSTRAINT fk_identity_verification_events_case FOREIGN KEY (verification_id)
        REFERENCES identity_verifications (id) ON DELETE CASCADE,
    CONSTRAINT fk_identity_verification_events_actor FOREIGN KEY (actor_user_id)
        REFERENCES users (id),
    CONSTRAINT chk_identity_verification_events_type CHECK (
        event_type IN ('REQUESTED', 'RESUBMITTED', 'APPROVED', 'REJECTED', 'REVOKED')
    ),
    CONSTRAINT chk_identity_verification_events_from_status CHECK (
        from_status IS NULL OR from_status IN ('PENDING', 'VERIFIED', 'REJECTED', 'REVOKED')
    ),
    CONSTRAINT chk_identity_verification_events_to_status CHECK (
        to_status IN ('PENDING', 'VERIFIED', 'REJECTED', 'REVOKED')
    )
);

CREATE INDEX idx_identity_verification_events_case_created
    ON identity_verification_events (verification_id, created_at, id);
CREATE INDEX idx_identity_verification_events_actor
    ON identity_verification_events (actor_user_id);
