ALTER TABLE users
    ADD COLUMN password_login_enabled BOOLEAN NOT NULL DEFAULT TRUE;

CREATE TABLE user_auth_identities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    provider VARCHAR(20) NOT NULL,
    provider_subject VARCHAR(255) NOT NULL,
    provider_email VARCHAR(320) NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_user_auth_identities PRIMARY KEY (id),
    CONSTRAINT fk_user_auth_identities_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT chk_user_auth_identities_provider CHECK (provider IN ('GOOGLE', 'APPLE')),
    CONSTRAINT uk_user_auth_identities_provider_subject UNIQUE (provider, provider_subject),
    CONSTRAINT uk_user_auth_identities_user_provider UNIQUE (user_id, provider)
);

CREATE INDEX idx_user_auth_identities_user ON user_auth_identities (user_id);
CREATE INDEX idx_user_auth_identities_provider_email ON user_auth_identities (provider, lower(provider_email));