ALTER TABLE jobs
    ADD COLUMN created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN taken_at TIMESTAMP(6) WITHOUT TIME ZONE NULL,
    ADD COLUMN completion_requested_at TIMESTAMP(6) WITHOUT TIME ZONE NULL,
    ADD COLUMN completed_at TIMESTAMP(6) WITHOUT TIME ZONE NULL,
    ADD COLUMN cancelled_at TIMESTAMP(6) WITHOUT TIME ZONE NULL;

ALTER TABLE jobs ALTER COLUMN created_at DROP DEFAULT;
ALTER TABLE jobs ALTER COLUMN updated_at DROP DEFAULT;

CREATE INDEX idx_jobs_status_created_at ON jobs (status, created_at DESC);
