CREATE TABLE stripe_payment_disputes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    version INTEGER NOT NULL DEFAULT 0,
    stripe_dispute_id VARCHAR(255) NOT NULL,
    stripe_payment_intent_id VARCHAR(255) NOT NULL,
    stripe_charge_id VARCHAR(255),
    user_id BIGINT NOT NULL,
    disputed_amount NUMERIC(19,2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    reason VARCHAR(64),
    stripe_status VARCHAR(32) NOT NULL,
    funds_withdrawn BOOLEAN NOT NULL DEFAULT FALSE,
    funds_reinstated BOOLEAN NOT NULL DEFAULT FALSE,
    wallet_recovered_amount NUMERIC(19,2) NOT NULL DEFAULT 0.00,
    wallet_returned_amount NUMERIC(19,2) NOT NULL DEFAULT 0.00,
    outstanding_amount NUMERIC(19,2) NOT NULL DEFAULT 0.00,
    recovery_sequence INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    funds_withdrawn_at TIMESTAMP(6) WITHOUT TIME ZONE,
    funds_reinstated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT pk_stripe_payment_disputes PRIMARY KEY (id),
    CONSTRAINT uk_stripe_payment_disputes_dispute UNIQUE (stripe_dispute_id),
    CONSTRAINT uk_stripe_payment_disputes_intent UNIQUE (stripe_payment_intent_id),
    CONSTRAINT fk_stripe_payment_disputes_payment FOREIGN KEY (stripe_payment_intent_id)
        REFERENCES payment_transactions (stripe_payment_intent_id),
    CONSTRAINT fk_stripe_payment_disputes_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT chk_stripe_payment_disputes_amount CHECK (disputed_amount > 0),
    CONSTRAINT chk_stripe_payment_disputes_currency CHECK (
        char_length(currency) = 3 AND currency = upper(currency)
    ),
    CONSTRAINT chk_stripe_payment_disputes_recovery CHECK (
        wallet_recovered_amount >= 0
        AND wallet_recovered_amount <= disputed_amount
        AND wallet_returned_amount >= 0
        AND wallet_returned_amount <= wallet_recovered_amount
        AND outstanding_amount >= 0
        AND outstanding_amount <= disputed_amount
        AND recovery_sequence >= 0
    )
);

CREATE INDEX idx_stripe_payment_disputes_user_outstanding
    ON stripe_payment_disputes (user_id, outstanding_amount)
    WHERE outstanding_amount > 0;

CREATE INDEX idx_stripe_payment_disputes_recovery_queue
    ON stripe_payment_disputes (updated_at, id)
    WHERE outstanding_amount > 0
      AND funds_withdrawn = TRUE
      AND funds_reinstated = FALSE;

CREATE TABLE stripe_payment_dispute_events (
    stripe_event_id VARCHAR(255) NOT NULL,
    stripe_dispute_id VARCHAR(255) NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    processed_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_stripe_payment_dispute_events PRIMARY KEY (stripe_event_id),
    CONSTRAINT fk_stripe_payment_dispute_events_dispute FOREIGN KEY (stripe_dispute_id)
        REFERENCES stripe_payment_disputes (stripe_dispute_id)
);

CREATE INDEX idx_stripe_payment_dispute_events_dispute
    ON stripe_payment_dispute_events (stripe_dispute_id, processed_at);
