CREATE TABLE stripe_refund_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    version INTEGER NOT NULL DEFAULT 0,
    user_id BIGINT NOT NULL,
    stripe_payment_intent_id VARCHAR(255) NOT NULL,
    request_key VARCHAR(128) NOT NULL,
    amount NUMERIC(19,2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    status VARCHAR(32) NOT NULL,
    stripe_refund_id VARCHAR(255),
    stripe_status VARCHAR(32),
    failure_reason VARCHAR(64),
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP(6) WITHOUT TIME ZONE,
    provider_event_created_at BIGINT,
    wallet_restored BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    submitted_at TIMESTAMP(6) WITHOUT TIME ZONE,
    resolved_at TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT pk_stripe_refund_requests PRIMARY KEY (id),
    CONSTRAINT uk_stripe_refund_requests_user_key UNIQUE (user_id, request_key),
    CONSTRAINT uk_stripe_refund_requests_refund UNIQUE (stripe_refund_id),
    CONSTRAINT fk_stripe_refund_requests_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_stripe_refund_requests_payment FOREIGN KEY (stripe_payment_intent_id)
        REFERENCES payment_transactions (stripe_payment_intent_id),
    CONSTRAINT chk_stripe_refund_requests_amount CHECK (amount > 0),
    CONSTRAINT chk_stripe_refund_requests_currency CHECK (
        char_length(currency) = 3 AND currency = upper(currency)
    ),
    CONSTRAINT chk_stripe_refund_requests_attempt CHECK (attempt_count >= 0),
    CONSTRAINT chk_stripe_refund_requests_status CHECK (
        status IN ('REQUESTED', 'DISPATCHING', 'PENDING', 'REQUIRES_ACTION', 'SUCCEEDED', 'FAILED', 'CANCELED')
    )
);

CREATE INDEX idx_stripe_refund_requests_payment
    ON stripe_refund_requests (stripe_payment_intent_id, status, id);

CREATE INDEX idx_stripe_refund_requests_dispatch
    ON stripe_refund_requests (next_attempt_at, id)
    WHERE status = 'REQUESTED';

CREATE INDEX idx_stripe_refund_requests_user
    ON stripe_refund_requests (user_id, created_at DESC, id DESC);

CREATE TABLE stripe_refund_events (
    stripe_event_id VARCHAR(255) NOT NULL,
    refund_request_id BIGINT NOT NULL,
    stripe_refund_id VARCHAR(255) NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    provider_created_at BIGINT,
    processed_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_stripe_refund_events PRIMARY KEY (stripe_event_id),
    CONSTRAINT fk_stripe_refund_events_request FOREIGN KEY (refund_request_id)
        REFERENCES stripe_refund_requests (id)
);

CREATE INDEX idx_stripe_refund_events_request
    ON stripe_refund_events (refund_request_id, processed_at);
