CREATE TABLE disputes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    version INTEGER NOT NULL DEFAULT 0,
    job_id BIGINT NOT NULL,
    opened_by_id BIGINT NOT NULL,
    assigned_admin_id BIGINT NULL,
    reason VARCHAR(32) NOT NULL,
    description VARCHAR(4000) NOT NULL,
    status VARCHAR(32) NOT NULL,
    previous_job_status VARCHAR(32) NOT NULL,
    resolution VARCHAR(32) NULL,
    admin_note VARCHAR(4000) NULL,
    opened_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    review_started_at TIMESTAMP(6) WITHOUT TIME ZONE NULL,
    resolved_at TIMESTAMP(6) WITHOUT TIME ZONE NULL,
    cancelled_at TIMESTAMP(6) WITHOUT TIME ZONE NULL,
    CONSTRAINT pk_disputes PRIMARY KEY (id),
    CONSTRAINT fk_disputes_job FOREIGN KEY (job_id) REFERENCES jobs (id),
    CONSTRAINT fk_disputes_opened_by FOREIGN KEY (opened_by_id) REFERENCES users (id),
    CONSTRAINT fk_disputes_assigned_admin FOREIGN KEY (assigned_admin_id) REFERENCES users (id)
);

CREATE INDEX idx_disputes_job_opened ON disputes (job_id, opened_at DESC);
CREATE INDEX idx_disputes_status_opened ON disputes (status, opened_at);
CREATE INDEX idx_disputes_opened_by ON disputes (opened_by_id);
CREATE INDEX idx_disputes_assigned_admin ON disputes (assigned_admin_id);

CREATE UNIQUE INDEX uk_disputes_active_job
    ON disputes (job_id)
    WHERE status IN ('OPEN', 'UNDER_REVIEW');

CREATE TABLE dispute_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    dispute_id BIGINT NOT NULL,
    actor_id BIGINT NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    note VARCHAR(4000) NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_dispute_events PRIMARY KEY (id),
    CONSTRAINT fk_dispute_events_dispute FOREIGN KEY (dispute_id) REFERENCES disputes (id),
    CONSTRAINT fk_dispute_events_actor FOREIGN KEY (actor_id) REFERENCES users (id)
);

CREATE INDEX idx_dispute_events_dispute_created ON dispute_events (dispute_id, created_at);
CREATE INDEX idx_dispute_events_actor ON dispute_events (actor_id);
