ALTER TABLE chat_messages
    ADD COLUMN client_message_id UUID NULL;

CREATE UNIQUE INDEX uk_chat_messages_sender_client
    ON chat_messages (sender_id, client_message_id)
    WHERE client_message_id IS NOT NULL;

CREATE INDEX idx_chat_messages_job_id_desc
    ON chat_messages (job_id, id DESC);

CREATE TABLE chat_read_states (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    job_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    last_read_message_id BIGINT NULL,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_chat_read_states PRIMARY KEY (id),
    CONSTRAINT uk_chat_read_states_job_user UNIQUE (job_id, user_id),
    CONSTRAINT fk_chat_read_states_job FOREIGN KEY (job_id) REFERENCES jobs (id),
    CONSTRAINT fk_chat_read_states_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_chat_read_states_message FOREIGN KEY (last_read_message_id) REFERENCES chat_messages (id)
);

CREATE INDEX idx_chat_read_states_user
    ON chat_read_states (user_id);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    recipient_id BIGINT NOT NULL,
    type VARCHAR(64) NOT NULL,
    title VARCHAR(160) NOT NULL,
    body VARCHAR(600) NOT NULL,
    job_id BIGINT NULL,
    dispute_id BIGINT NULL,
    read_at TIMESTAMP(6) WITHOUT TIME ZONE NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_notifications PRIMARY KEY (id),
    CONSTRAINT fk_notifications_recipient FOREIGN KEY (recipient_id) REFERENCES users (id),
    CONSTRAINT fk_notifications_job FOREIGN KEY (job_id) REFERENCES jobs (id),
    CONSTRAINT fk_notifications_dispute FOREIGN KEY (dispute_id) REFERENCES disputes (id)
);

CREATE INDEX idx_notifications_recipient_created
    ON notifications (recipient_id, created_at DESC);

CREATE INDEX idx_notifications_recipient_unread
    ON notifications (recipient_id, created_at DESC)
    WHERE read_at IS NULL;
